---
- hosts: localhost
  tasks:
      - name: show sshkey
        debug:
          msg: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"
  tasks:
      - name: create sshkey file
        community.general.packet_sshkey:
          key: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"
    
