---
- name: Prepare
  task:

    - name: prepare
      debug:
        msg: "prepare"
- hosts: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"
  vars:
    greeting: Hello world!
    host: 13.114.201.131
    loggingType: ssh
    port: 22
    username: ec2-user

  tasks:
  - name: Ansible Basic Variable Example
    debug:
      msg: "{{ greeting }}"
      msg: "{{ host }}"
      msg: "{{ loggingType }}"
      msg: "{{ port }}"
      msg: "{{ username }}"

