--- 
- 
  hosts: localhost
  name: "parse file sshkey!"
  vars:
    greeting: Hello world!
    host: 13.114.201.131
    loggingType: ssh
    port: 22
    username: ec2-user
    sshkey: asdasd
 
  tasks: 
    - debug: msg="{{ sshkey }}"
    
  tasks:
    community.general.packet_sshkey:
      key: "{{ sshkey }}"
