---
- hosts: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"
  tasks:
    - name: Install apache packages 
      yum:
        name: httpd
        state: present
      debug: msg="{{  lookup('vault_1', 'kv_awx/ansible', 'testhost') }}"

