---
- name: Create sshkey from string
  hosts: localhost
  vars:
    sskeystring: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"
  tasks:
    community.general.packet_sshkey:
      key: "{{ sskeystring }}"
    
