---
- hosts: localhost
  tasks:
      - name: show sshkey, create sshkey file
        debug:
          msg: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"          
        community.general.packet_sshkey:
          key: "{{ lookup('env','TOWER_HOST') | default('default_value') }}"
    
