---
- name: Show credentials from vault
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Display Username from Vault
      debug:
        msg: "{{ ansible_username }}"
        
    - name: Display Password from Vault
      debug:
        msg: "{{ ansible_password }}"
    - name: Get a secret from using with_vault
      debug:
        msg="{{ item.value }}"
    - name: Test connection to host
      ping:    
