---
- name: Show credentials from vault
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Display default_value from Vault
      debug: msg="{{ lookup('env','TOWER_HOST') | default('default_value') }}"
        
    
    - name: Display testhost from Vault
      password: "{{ lookup('vault', 'secret=kv_awx/ansible')['testhost']}}"
        
    - name: Test connection to host
      ping:    
