---
- name: Show credentials from vault
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Display test host from Vault
      debug:
        msg: "{{ testhost }}"
    - name: Test connection to host
      ping:    
