---
- name: Show credentials from vault
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Display testhost from Vault
      debug:
        msg: "{{  lookup('vault', 'kv_awx/ansible', 'testhost') }}"
